from .categoriaController import CategoriaController
from .pontoTuristicoController import PontoTuristicoController
from .userController import UserController
from .avaliacaoController import AvaliacaoController
from .promocaoController import PromocaoController
from .favoritoController import FavoritoController
from .historicoSenhaController import HistoricoSenhaController